export const INITIAL_PRODUCTS = [
  {
    _id: 'prod-001',
    name: 'AeroSound Pro Wireless ANC Headphones',
    description: 'Premium active noise-cancelling wireless headphones with 40-hour battery life, high-resolution spatial audio, and memory-foam plush earcups.',
    price: 199.99,
    category: 'Electronics',
    brand: 'AeroSound',
    countInStock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    numReviews: 42,
    isFeatured: true,
  },
  {
    _id: 'prod-002',
    name: 'Zenith Custom RGB Mechanical Keyboard',
    description: 'Hot-swappable mechanical switches with custom PBT dye-sub keycaps, sound-dampening silicone gasket mount, and programmable wireless connectivity.',
    price: 129.5,
    category: 'Electronics',
    brand: 'Zenith',
    countInStock: 18,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    numReviews: 38,
    isFeatured: true,
  },
  {
    _id: 'prod-003',
    name: 'Horizon 34-inch Curved UltraWide Monitor',
    description: 'Immersive WQHD 144Hz IPS display featuring 99% sRGB color accuracy, HDR400 certification, and USB-C 90W power delivery for seamless productivity.',
    price: 499.0,
    category: 'Electronics',
    brand: 'Horizon Display',
    countInStock: 8,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    numReviews: 19,
    isFeatured: false,
  },
  {
    _id: 'prod-004',
    name: 'Vanguard Full-Grain Leather Commuter Backpack',
    description: 'Handcrafted water-resistant commuter pack with a dedicated 16-inch padded laptop compartment, luggage pass-through sleeve, and antique brass hardware.',
    price: 145.0,
    category: 'Fashion',
    brand: 'Vanguard Goods',
    countInStock: 14,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    numReviews: 54,
    isFeatured: true,
  },
  {
    _id: 'prod-005',
    name: 'Atelier Minimalist Breathable Linen Shirt',
    description: 'Relaxed-fit pure European flax linen button-up designed for warm-weather breathability, natural drape, and timeless casual elegance.',
    price: 64.99,
    category: 'Fashion',
    brand: 'Atelier',
    countInStock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    numReviews: 23,
    isFeatured: false,
  },
  {
    _id: 'prod-006',
    name: 'Chronos Heritage Automatic Chronograph Watch',
    description: 'Precision Japanese automatic movement housed in a 316L stainless steel case with sapphire crystal glass and genuine Italian calfskin strap.',
    price: 289.0,
    category: 'Fashion',
    brand: 'Chronos',
    countInStock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    numReviews: 31,
    isFeatured: true,
  },
  {
    _id: 'prod-007',
    name: 'ErgoPro High-Back Mesh Ergonomic Chair',
    description: 'Advanced dynamic lumbar support, 4D adjustable armrests, breathable temperature-regulating mesh, and 135-degree smooth recline tilt mechanism.',
    price: 320.0,
    category: 'Home & Living',
    brand: 'ErgoPro',
    countInStock: 6,
    imageUrl: 'https://images.unsplash.com/photo-1580481077195-c3a824552965?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    numReviews: 67,
    isFeatured: true,
  },
  {
    _id: 'prod-008',
    name: 'BaristaCraft Artisanal Pour-Over Coffee Set',
    description: 'Heat-resistant borosilicate glass carafe with double-mesh stainless steel reusable dripper, olive wood collar, and precision gooseneck kettle.',
    price: 58.5,
    category: 'Home & Living',
    brand: 'BaristaCraft',
    countInStock: 22,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    numReviews: 45,
    isFeatured: false,
  },
  {
    _id: 'prod-009',
    name: 'Aura Minimalist Nordic Ambient Smart Lamp',
    description: 'Stepless dimming LED glow with tunable warm-to-cool white light, capacitive touch base, and wireless phone fast-charging pad.',
    price: 79.99,
    category: 'Home & Living',
    brand: 'Aura Living',
    countInStock: 16,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    numReviews: 18,
    isFeatured: false,
  },
  {
    _id: 'prod-010',
    name: 'TitanPro Pulse Multisport Smartwatch',
    description: 'Continuous optical heart-rate monitoring, onboard GPS, SpO2 sensor, water resistance up to 50 meters, and 14-day ultra battery mode.',
    price: 169.95,
    category: 'Fitness',
    brand: 'TitanPro',
    countInStock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    numReviews: 50,
    isFeatured: true,
  },
];
